on : push
jobs : 
      first-job :
        runs-on : ubuntu-latest
        steps :
              - run : node --version 
              - run : npm --version 
      Second-job :
        runs-on : ubuntu-latest
        steps :
              - run : node --version 
              - run : npm --version 
              - uses : actions/checkout@v4
              - run : node index.js
      third-job :
        runs-on : ubuntu-latest
        steps :
              - run : node --version 
              - run : npm --version 
              - uses : actions/checkout@v4
              - run : npm ci
              - run : npx eslint .
              - run : node index.js
              - run : node script.js




# on : push
# jobs : 
#       first-job :
#         runs-on : windows-latest, macos-latest
#         steps :
#               - run : node --version 
#               - run : npm --version 
