on : push
jobs : 
      first-job :
        runs-on : ubuntu-latest
        steps :
              - run : node --version 
              - run : npm --version 




# on : push
# jobs : 
#       first-job :
#         runs-on : windows-latest, macos-latest
#         steps :
#               - run : node --version 
#               - run : npm --version 
